services:
  redis:
    container_name: awesome-infra-redis
    image: redis:5.0
    platform: linux/amd64
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: awesome-infra-rabbitmq
    image: rabbitmq:4-management-alpine
    platform: linux/amd64
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminpass1!
    ports:
      - "5672:5672"
      - "15672:15672"
