apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.21
        resources:
          limits:
            cpu: 600m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: skcc
