server:
  port: 8080

mybatis:
  config-location: file:/config/mybatis-config-mysql.xml

spring:
  config:
    import: 
      - file:/config/application-prd.yml

logging:
  level:
    org.springframework.boot: INFO
    org.springframework.core : INFO

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
