resources:
- ../../../../base/awesome

nameSuffix: "-cart"

labels:
- includeTemplates: true
  pairs:
    app: awesome-cart
    env: prd
    system: awesome

images:
- name: awesome
  newName: acraz104ktds20260522.azurecr.io/awesome-cart
  newTag: latest

configMapGenerator:
  - name: config
    files:
      - config/application.yml
      - config/application-prd.yml
      - config/data-mysql.sql
      - config/mybatis-config-mysql.xml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

patches:
- patch: |
    kind: not-important
    metadata:
      name: awesome
    spec:
      template:
        spec:
          containers:
            - name: springboot
              env:
                - name: JDK_JAVA_OPTIONS
                  value: "-XX:+UseContainerSupport -javaagent:/app/bin/opentelemetry-javaagent.jar"
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: http://otel-apps.otel-collector:4318
                - name: OTEL_SERVICE_NAME
                  value: awesome-cart
                - name: OTEL_RESOURCE_ATTRIBUTES
                  value: "service.namespace=awesome"
                - name: OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED
                  value: 'true'
                - name: OTEL_INSTRUMENTATION_SPRING_BOOT_ACTUATOR_AUTOCONFIGURE_ENABLED
                  value: 'true'
                - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
                  value: 'true'
                - name: OTEL_INSTRUMENTATION_LOGBACK_ENABLED
                  value: 'true'
                - name: OTEL_INSTRUMENTATION_COMMON_EXPERIMENTAL_CONTROLLER_TELEMETRY_ENABLED
                  value: 'false'
                - name: OTEL_INSTRUMENTATION_RABBITMQ_EXPERIMENTAL_SPAN_ATTRIBUTES
                  value: 'true'
              volumeMounts:
                - name: config
                  mountPath: "/config"
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: config
                items:
                  - key: application.yml
                    path: application.yml
                  - key: application-prd.yml
                    path: application-prd.yml
                  - key: data-mysql.sql
                    path: data-mysql.sql
                  - key: mybatis-config-mysql.xml
                    path: mybatis-config-mysql.xml
  target:
    kind: (Deployment)

replacements:
  - source:
      kind: Deployment
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app
      - select:
          kind: Service
        fieldPaths:
          - spec.selector.app
  - source:
      kind: ConfigMap
      name: config
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - "spec.template.spec.volumes.0.configMap.name"
