spring:
  config:
    import: 
      - file:/config/application-prd.yml

logging:
  level:
    org.springframework.boot: INFO
    org.springframework.core : INFO

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
